version: "3.8"

services:
  mongodb:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=viva
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  mongo-init:
    image: mongo:latest
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: on-failure:3
    command: >
      mongosh --host mongodb:27017 --eval '
        config = {
          "_id": "rs0",
          "members": [
            { "_id": 0, "host": "localhost:27017", "priority": 1 }
          ]
        };
        rs.initiate(config);
        while (!rs.isMaster().ismaster) {
          print("Waiting for replica set initialization...");
          sleep(1000);
        }
        print("Replica set initialized successfully!");
      '

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: